# Generated by Django 5.2.14 on 2026-05-13 19:20

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new_launch', 'New Launch'), ('under_construction', 'Under Construction'), ('ready_to_move', 'Ready to Move'), ('sold_out', 'Sold Out')], default='under_construction', max_length=24)),
                ('property_type', models.CharField(blank=True, max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('price_starting_lacs', models.DecimalField(blank=True, decimal_places=2, help_text='Machine-sortable starting price in lakhs (₹).', max_digits=10, null=True)),
                ('price_display', models.CharField(blank=True, help_text="Free-text price label shown on the site, e.g. '80 Lacs*'.", max_length=60)),
                ('size_display', models.CharField(blank=True, help_text="e.g. '360 Sq.Ft. onwards'.", max_length=80)),
                ('rera_number', models.CharField(blank=True, max_length=60)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps iframe `src` URL.', max_length=600)),
                ('cover_image', models.ImageField(blank=True, upload_to=projects.models._project_cover_path)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='projects', to='catalog.amenity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='catalog.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='catalog.city')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='catalog.developer')),
            ],
            options={
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='projects.project')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=projects.models._project_gallery_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Property status', 'Price Starts from', 'Sizes', 'Developer', 'Property Type'.", max_length=60)),
                ('value', models.CharField(max_length=120)),
                ('icon_key', models.CharField(blank=True, help_text='String identifier the frontend maps to an icon asset.', max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='projects.project')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'is_featured'], name='projects_pr_is_publ_4f7a90_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['city', 'category'], name='projects_pr_city_id_9d83be_idx'),
        ),
    ]
