# Generated by Django 5.2.14 on 2026-05-13 19:44

import common.upload_paths
import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Used by the frontend `alt` attribute (a11y + SEO).', max_length=200),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=common.upload_paths.project_cover_path, validators=[common.validators.validate_image_size, common.validators.validate_image_dimensions, common.validators.validate_image_mimetype]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=common.upload_paths.project_gallery_path, validators=[common.validators.validate_image_size, common.validators.validate_image_dimensions, common.validators.validate_image_mimetype]),
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='JPEG / PNG / WEBP / PDF, up to 10 MB.', upload_to=common.upload_paths.floor_plan_path, validators=[common.validators.validate_floor_plan])),
                ('label', models.CharField(blank=True, help_text="e.g. 'Ground Floor', '2 BHK Type A'.", max_length=80)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='projects.project')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
