# Generated by Django 5.2.14 on 2026-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_amenity_icon_alter_developer_logo'),
        ('projects', '0002_projectimage_alt_text_projectimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-published_at'], name='projects_pr_publish_2cc856_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['price_starting_lacs'], name='projects_pr_price_s_33d862_idx'),
        ),
    ]
