# Generated by Django 5.2.14 on 2026-05-13 20:44

import common.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_amenity_icon_alter_developer_logo'),
        ('projects', '0003_project_projects_pr_publish_2cc856_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new_launch', 'New Launch'), ('under_construction', 'Under Construction'), ('ready_to_move', 'Ready to Move'), ('sold_out', 'Sold Out')], default='under_construction', max_length=24)),
                ('property_type', models.CharField(blank=True, max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('price_starting_lacs', models.DecimalField(blank=True, decimal_places=2, help_text='Machine-sortable starting price in lakhs (₹).', max_digits=10, null=True)),
                ('price_display', models.CharField(blank=True, help_text="Free-text price label shown on the site, e.g. '80 Lacs*'.", max_length=60)),
                ('size_display', models.CharField(blank=True, help_text="e.g. '360 Sq.Ft. onwards'.", max_length=80)),
                ('rera_number', models.CharField(blank=True, max_length=60)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps iframe `src` URL.', max_length=600)),
                ('cover_image', models.TextField(blank=True, max_length=100, validators=[common.validators.validate_image_size, common.validators.validate_image_dimensions, common.validators.validate_image_mimetype])),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category')),
                ('city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.city')),
                ('developer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.developer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
