# Generated by Django 5.2.14 on 2026-05-13 19:44

import common.upload_paths
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(blank=True, upload_to=common.upload_paths.amenity_icon_path, validators=[common.validators.validate_image_size, common.validators.validate_image_mimetype]),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.upload_paths.developer_logo_path, validators=[common.validators.validate_image_size, common.validators.validate_image_mimetype]),
        ),
    ]
