# Generated by Django 5.2.14 on 2026-05-13 19:44

import common.upload_paths
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.upload_paths.cms_hero_path, validators=[common.validators.validate_image_size, common.validators.validate_image_dimensions, common.validators.validate_image_mimetype]),
        ),
    ]
