# Generated by Django 5.2.14 on 2026-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('template_base', models.CharField(help_text="Template name without extension (e.g. 'emails/inquiry_property').", max_length=120)),
                ('recipients', models.TextField(help_text='Comma-separated list of recipient addresses.')),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('last_retried_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'failed notification',
                'verbose_name_plural': 'failed notifications',
                'ordering': ('-created_at',),
            },
        ),
    ]
